# Generated by Django 4.0.4 on 2022-05-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermartApp', '0003_order_carddetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermartApp.account')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermartApp.product')),
            ],
        ),
    ]
